
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BangueWs", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9191/?wsdl")
public class BangueWs
    extends Service
{

    private final static URL BANGUEWS_WSDL_LOCATION;
    private final static WebServiceException BANGUEWS_EXCEPTION;
    private final static QName BANGUEWS_QNAME = new QName("http://ws/", "BangueWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANGUEWS_WSDL_LOCATION = url;
        BANGUEWS_EXCEPTION = e;
    }

    public BangueWs() {
        super(__getWsdlLocation(), BANGUEWS_QNAME);
    }

    public BangueWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANGUEWS_QNAME, features);
    }

    public BangueWs(URL wsdlLocation) {
        super(wsdlLocation, BANGUEWS_QNAME);
    }

    public BangueWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANGUEWS_QNAME, features);
    }

    public BangueWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BangueWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANGUEWS_EXCEPTION!= null) {
            throw BANGUEWS_EXCEPTION;
        }
        return BANGUEWS_WSDL_LOCATION;
    }

}
